### PR TITLE
Solana improvements

### LINKED ISSUE #45: Solana - List Agreements

### LINKED ISSUE #95: Fixes Solana
- all pages must work without crash
- no throwing errors on console
- timeout without timeout
-

### PR DESCRIPTION
**Pull request by nomadbitcoin**
Agreements are being shown to Solana and some bugs have been fixed

closes #45 
closes #95

### CODE REVIEW

File: components/AgreementList/AgreementList.js [hunk 1]
```diff
@@ -64,49 +58,36 @@ function AgreementList(props) {
...
+      paymentValue,
+      agreementId,
+    };
+  
+    const onConfirmation = () => {
       setShowPaymentInput(false)
-    }
-  }
+      setPaymentValue("");
+      setTimeout(() => {
```
Comment (danicuki) [inline components/AgreementList/AgreementList.js:72]: ugly stuff

File: components/AgreementList/AgreementList.js [hunk 2]
```diff
@@ -169,12 +155,12 @@ function AgreementList(props) {
               </p>
 
               <p>
-                <strong>{t("payment-amount")}</strong>
-                {parseFloat(ethers.utils.formatUnits(agreement.payment.amount, 18))
-                  .toFixed(2)
-                  .replace(/\.00$/, "")}{" "}
-                USD
+                  <strong>{t("payment-amount")}</strong>
+                  {agreement.payment.amount && !isNaN(agreement.payment.amount)
```
Comment (danicuki) [inline components/AgreementList/AgreementList.js:159]: Extract this to a function that receives the amount and returns the valid string

File: components/AgreementList/tokenConfig.js [hunk 3]
```diff
@@ -0,0 +1,23 @@
+// tokenConfig.js
+
+import tokens from "../../public/allowedTokens.json";
+
+const ENV = process.env.NODE_ENV;
+const FAKE_SOL = process.env.NEXT_PUBLIC_SOLANA_FAKE_STABLE_ADDRESS;
+const FAKE_EVM = process.env.NEXT_PUBLIC_FAKE_STABLE_ADDRESS;
+
+export const getTokens = (chain) => {
+    if (ENV !== 'development') {
```
Comment (danicuki) [inline components/AgreementList/tokenConfig.js:10]: this should not be here. There must be a function `getTokens` on each chain implementation that returns the token list. We can't have any chain specific stuff in the common interface.

File: public/locales/en-US/translation.json [hunk 4]
```diff
@@ -71,6 +71,7 @@
   "skills-tooltip": "The sum must equal 100%",
   "add": "add",
   "add-btn": "Add",
-  "agreement-created": "Agreement created!",
-  "agreement-pending": "Transaction is still pending, please wait."
+  "transaction-success": "Transaction successful!",
```
Comment (danicuki) [inline public/locales/en-US/translation.json:74]: what about translations for pt-BR?

**Review by danicuki — APPROVED** [review]
